# Generated by Django 5.2.4 on 2025-07-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fId', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(choices=[('MATH', 'Mathematics'), ('SCI', 'Science'), ('HIST', 'History'), ('ENG', 'English'), ('CS', 'Computer Science')], max_length=50)),
                ('marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Student Subject Mark',
                'verbose_name_plural': 'Student Subject Marks',
                'unique_together': {('student_name', 'subject_name')},
            },
        ),
    ]
