# Generated by Django 5.2.4 on 2025-07-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marksManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
