# Generated by Django 5.2.4 on 2025-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksManagement', '0002_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
