# Generated by Django 5.2.4 on 2025-07-22 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksManagement', '0003_alter_student_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Marks cannot be less than 0.'), django.core.validators.MaxValueValidator(100, message='Marks cannot be greater than 100.')]),
        ),
    ]
